# fly.toml app configuration file generated for rainfall-alarm-kr on 2026-02-27T01:06:42+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rainfall-alarm-kr'
primary_region = 'nrt'

[build]

[env]
  NODE_ENV = 'production'
  PORT = '3000'
  DB_DIR = '/app/db'

[mounts]
  source = 'rainfall_data'
  destination = '/app/db'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 200
    soft_limit = 100

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
